version: '3.7'

networks:
  compose-bridge:
    driver: bridge

services:
  fast-api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app:cached
    image: fast_api
    depends_on:
      - mysql
    restart: "on-failure"
    networks:
      - compose-bridge
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=client_db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - compose-bridge
    ports:
      - 3306:3306  
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local