version: '3.7'

networks:
  compose-bridge:
    driver: bridge

services:
  fast-api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/app:cached
    image: fast_api
    restart: "on-failure"
    networks:
      - compose-bridge
volumes:
  db:
    driver: local